export type Sexo = 'M' | 'F';

export const ETIQUETA_SEXO: Record<Sexo, string> = { M: 'Masculino', F: 'Femenino' };

export const esSexo = (v: unknown): v is Sexo => v === 'M' || v === 'F';

const lista = (s: string): Set<string> => new Set(s.split(/\s+/).filter(Boolean));

// Nombres frecuentes (sin tildes). Los terminados en A/O no listados se infieren por la terminación.
const FEMENINOS = lista(`
  ANA ADRIANA AIDA ALEJANDRA ALICIA ALBA ALEXANDRA ALIDA AMELIA ANDREA ANGELA ANGELICA ANGELY ANGELINA ARACELIS ARELIS ARGELIS
  ARIANA ARIANNY AURA AURORA BARBARA BEATRIZ BELKIS BETTY BLANCA BRENDA CAREN CARIDAD CARLA CARMEN CAROLINA CATHERINE CECILIA
  CELESTE CLARA CLAUDIA CONSUELO CORINA CRISTINA DAISY DAMARIS DANIELA DAYANA DELIA DIANA DILIA DORIS DULCE EDITH ELADIA ELENA
  ELIZABETH ELSA ELVIRA EMILIA ESTHER ESTELA EULALIA EVA FABIOLA FATIMA FRANYELI FRANYELY GABRIELA GENESIS GISELA GLADYS GLORIA
  GRACIELA HAYDEE HILDA IDALIA INES IRENE IRIS ISABEL ISABELLE ISABELA ISBELIA JENIFER JENNIFER JESSICA JOSEFA JOSEFINA JUANA
  JULIA JULIANA JULIANY KARLA KARLISMAR KATIUSKA KATHERINE KARINA LAURA LEIDA LEIDY LILIANA LIZ LIZBETH LORENA LOURDES LUCIA
  LUISA LUZ MABEL MAGALY MARBELLA MARGARITA MARIA MARIANA MARIELA MARLENE MARTHA MARISOL MARISELA MAYERLIN MERCEDES MILAGROS
  MIRIAM MYRIAM MYRIAN MIRIAN MISHAELL MONICA NANCY NAIDIMAR NATALI NATALIA NAYLETH NELLY NILDA NOHEMI NORA NORMA NURIS
  OLGA ORIANA PATRICIA PAOLA PAULA PETRA PRISCILA PRISCILLA RAQUEL REBECA ROSA ROSALIA ROSARIO ROSELYN ROSMARY RUTH SANDRA
  SARA SARAI SELENA SENOBIA SILVIA SOFIA SOL SOLANGEL SONIA STEFANY STEPHANY SUSANA TAMARA TERESA TRINIDAD VALENTINA VANESSA
  VERONICA VICTORIA VIOLETA VIRGINIA XIOMARA YAIGLIS YAJAIRA YANETH YELI YELITZA YENNY YESENIA YESIKA YESSICA YOHANA YOISSY
  YOLANDA YUDITH YUSLEIDI YULIMAR YULIANA YUSBELY ZORAIDA
`);

const MASCULINOS = lista(`
  ABRAHAM ADRIAN ALBERTO ALEXANDER ALFONSO ALFREDO ALI ANDRES ANGEL ANIBAL ANTONIO ARMANDO ARNOLDO ARTURO AUGUSTO BERNARDO
  BRAYAN BRIAN BRUNO CARLOS CESAR CRISTIAN CRISTOBAL DANIEL DARIO DAVID DIEGO DOMINGO EDGAR EDUARDO EDWIN ELIAS ELVIS EMILIO
  ENRIQUE ERNESTO EUDOMAR EUGENIO FABIAN FEDERICO FELIPE FELIX FERNANDO FRANCISCO FRANKLIN FREDDY GABRIEL GERARDO GERMAN
  GILBERTO GONZALO GREGORIO GUILLERMO GUSTAVO HECTOR HENRY HERNAN HUGO HUMBERTO IGNACIO ISAAC ISMAEL IVAN JAIME JAVIER JEAN
  JEFFERSON JESUS JHON JHONNY JHOSEP JHOSEPH JOEL JORGE JOSE JOSEPH JOSUE JUAN JULIAN JULIO KEVIN LEANDER LEONARDO LEORNANDO
  LEONEL LUIS MANUEL MARCOS MARIO MARTIN MATEO MAURICIO MIGUEL NELSON NESTOR NICOLAS OMAR OSCAR OSWALDO PABLO PASCUAL PEDRO
  RAFAEL RAMON RAUL REINALDO RICARDO ROBERTO RODOLFO RODRIGO ROGELIO ROLANDO RUBEN SAMUEL SANTIAGO SEBASTIAN SERGIO SIMON
  TEODORO THIAGO TOMAS VICENTE VICTOR WILLIAM WILMER YOHAN YORMAN ZAIR
`);

// Nombres usados por ambos sexos o ilegibles: se dejan sin determinar para que recepción los defina.
const AMBIGUOS = lista('ALEXIS ARIEL GUADALUPE YOHANIS YUDIMAR EUDIMAR ISYEL GLEININ SHIILIWALA ZENAIR JORDAN DANI');

function normalizar(texto: string): string {
  return texto.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase().trim();
}

/**
 * Sugiere el sexo a partir del primer nombre (el sistema guarda "NOMBRE APELLIDO").
 * Devuelve null si no se puede determinar con razonable confianza; es solo una sugerencia que recepción confirma.
 */
export function inferirSexo(nombreCompleto: string): Sexo | null {
  const primero = normalizar(nombreCompleto).split(/\s+/)[0] ?? '';
  if (primero.length < 2 || AMBIGUOS.has(primero)) return null;
  if (FEMENINOS.has(primero)) return 'F';
  if (MASCULINOS.has(primero)) return 'M';
  if (primero.endsWith('A')) return 'F';
  if (primero.endsWith('O')) return 'M';
  return null;
}
